[package]
name = "semantic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
lexical = { path = "../lexical" }
grammar = { path = "../grammar" }
try_match = "0.3"
